version: '3'
services:
  roboter_chrome:
    image: ppodgorsek/robot-framework:latest
     #
     # shared memory size configuration
     # even headless chrome needs some swapping memory, this is configured here
     # and set to a reasonable amount if browser crashes without other reasons
     # checking the free memory is quite an issue
     #
    shm_size: '4gb'
    volumes:
      - C:\Users\ciara\qa-demo-auto-testing\reports:/opt/robotframework/reports
      - C:\Users\ciara\qa-demo-auto-testing\test\:/opt/robotframework/tests
      - C:\Users\ciara\qa-demo-auto-testing\test\resources:/opt/robotframework/tests/resources
    environment:
      - LOG_LEVEL=vv